travis:
  secure:
    BINSTAR_TOKEN: o7Oq+/pe88oF0l0uZIePbYWvWOQg22okBmw2MxrmdhUTVkQqC6f/ykeY8i+qWkKLdfkC19JUIr9+ol6NNj9aZBJxoLpsynZ0hNuU9uLixtRmtngbvO2vocN/hn15EfcffUNgc0CVfBQveO/lUhbvM8wC7/g4Ftjxier94wo9i1sKGPdb7ZhOet57eSS7Sb+LGhncCc9Hq4gmTc0y8EywUMyavtUOPhBmcmPutrvsIzu/TAl3OYp7Z+X9EYqB0VEYs3qyCfnNFodKVhc1JIwp5ILL2dTxXdNLhndqlx6YUb2c2fqQl711vuXI6e6QLKYnnhkVl3c+fuiE1GynA0JJiMQLVfOzLHb6NHF14ap4A7MSdyCe5NSGLt8WQpPUekb3vhHEyaTx6JxmRV90qU/u5CruCS3zlwcwAMqnmPc+t7o2ODauErGFSVXnU1OjYG2fPm4/mZ9BozAwwuXeh2/wJKNLue64aeoFgcFsChgqGWmW4qPr2/G8lmv4ac53P3pJLRJXCGvmcofOAFKY61evW9V2VIqu8aCoZkJfcO1Dhn8WLvGS2LHbePk9Fxl2XFEpuQCjD3pVuyy39DWnfvLK4+JqnY6yHANuW+CNTOz0ChKhE8Z/KQbTDntnpwtu73Pzx4veMKwuR5z/z6SMXaCz8sJ4W8zg/GnWE/q5iFrFpi0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
