travis:
  secure:
    BINSTAR_TOKEN: n84CaiQh0UeHEWwNWDf1VzqKn/Yp9dXpzkKyup2RBlxGPcJ88swNPI7hYq3Y9nUoyYkBPz69xegwIeEKt6i7G/wQnKd4yHBNK8a093F63oMelouknj26IyRD7sE8SE0cpWSPqSiiatmiHfvi/bEGZ70QD708WF4RjDzOSSaVVqAzS15C1RnGmCJj9ELs9QNAPsNUBIGITJ7icmSal3TL7zYlumVJeQ7zwsrPXdFMG/pD2e+/KbnVxAFEgHvgsxb4ZexwEMCOBE3JvLl8CfFcGnPhLRv20kwMExWzci9LxWOYPKCkIMEIOWHmY5TyGH5q2nDIs6MUmHs6svIByiw049OMYM3rPsMVUQEAT+Dy1N0viHV98X1ai14qRf14UUGmBDFFvgxfNavm06oIdLI6vfqWp9/D6sSpeFPopN2gW3ORX887BqGRZAJ+qrRPZ7htEgAvMAKP/DWHGeIKvW/CPygX5ir4fb87NyLc3kiJuNDErLeL+C/F5wlWBllrn4jAPz9Sk+hvCGS2AsDTTLQ4F1s/cIWyIm7A/A0ZkQWNrihSmVjV8eCxhBuJsre6i1EXGUFRx9iqqLjmhT+i1IOuQ3XJEMh/u8kmZ9m7xRfMc3oDa5sRk1vo4J7s8HsCeT0lkuAtaiOmd2BUQHGelJQZC1XQxbTOjfJzjA0kCIjSdWg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
